# Generated by Django 6.0.7 on 2026-08-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_github_id_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
