# Generated by Django 6.0.7 on 2026-08-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_github_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wakatime_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
