# Generated by Django 6.0.7 on 2026-08-09 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_repo_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=250)),
                ('html_url', models.URLField()),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField()),
                ('private', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40, unique=True)),
                ('message', models.TextField()),
                ('author_name', models.CharField(max_length=150)),
                ('author_date', models.DateTimeField()),
                ('html_url', models.URLField()),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.repo')),
            ],
        ),
    ]
