# Generated by Django 6.0.7 on 2026-08-21 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='sha',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='repo',
            name='github_repo_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='commit',
            constraint=models.UniqueConstraint(fields=('repo', 'sha'), name='unique_commit_per_repo'),
        ),
        migrations.AddConstraint(
            model_name='repo',
            constraint=models.UniqueConstraint(fields=('user', 'github_repo_id'), name='unique_repo_per_user'),
        ),
    ]
