# Generated by Django 6.0.7 on 2026-09-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='font',
            field=models.CharField(default='sans', max_length=12),
        ),
    ]
