# Generated by Django 6.0.7 on 2026-09-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='font_size',
            field=models.PositiveSmallIntegerField(default=16),
        ),
    ]
